#!/bin/bash
set -e

# This script is designed to be run as part of the strap bootstrapping process.
# Assume that git and brew are installed. Assume that dotfiles repo is in ~.

# GitHub repos to download
GITHUB_USER="mkcode"
USER_CONFIG_REPOS=("prezto" "spacemacs")

# Install location of system configuration repos
CONFIG_REPO_PREFIX=~/src/pocket
DOTFILES_REPO_PATH="$CONFIG_REPO_PREFIX/dotfiles"

# Get all of our config related repos in one place
mkdir -p "$CONFIG_REPO_PREFIX"

ln -sf ~/.dotfiles "$DOTFILES_REPO_PATH"
# if [ -d ~/.dotfiles ]; then
#   mv ~/.dotfiles "$DOTFILES_REPO_PATH"
#   ln -sf ~/.dotfiles "$DOTFILES_REPO_PATH"
#   echo "Moved dotfiles repo to '$DOTFILES_REPO_PATH'"
# fi

if [ -n "$USER_CONFIG_REPOS" ]; then
  (
    cd "$CONFIG_REPO_PREFIX"
    for repo in "${USER_CONFIG_REPOS[@]}"
    do
      if [ ! -d "$repo" ]; then
        REPO_URL="https://github.com/$GITHUB_USER/$repo"
        git clone --recurse-submodules "$REPO_URL"
      else
        (
          cd "$repo"
          git pull --recurse-submodules --autostash
        )
      fi
    done
  )
fi

ln -sf "$DOTFILES_REPO_PATH/Brewfile" ~/.Brewfile
ln -sf "$DOTFILES_REPO_PATH/rcrc" ~/.rcrc

ln -sf "$CONFIG_REPO_PREFIX/spacmacs" ~/.spacemacs
ln -sf "$CONFIG_REPO_PREFIX/prezto" ~/.zprezto
