#!/bin/bash
set -e

# This script is designed to be run as part of the strap bootstrapping process.
# Assume that git and brew are installed. Assume that dotfiles repo is in ~.

# Install location of system configuration repos
CONFIG_REPO_PREFIX=~/src/pocket

ITERM2_PREFS_FILE="$CONFIG_REPO_PREFIX/dotfiles/extras/com.googlecode.iterm2.plist"

# Run rcup to link all files to home
rcup

# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$ITERM2_PREFS_FILE"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Set shell to be homebrew installed zsh
dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh

# We want our dotfiles dir to live elsewhere and had previously symlinked toe
# there from home. Having a symlink to dotfiles crashes strap and makes it not
# idempotent. So we now delete the symlink so strap stays idempotent.
rm ~/.dotfiles
